### ISSUE TITLE
[BUG] 'Incorrect type. Expected "array".' w/ "✅ Label bug reports"

### ISSUE THREAD

**Issue by classicrocker883** [MarlinFirmware/Marlin#26489]
### Did you test the latest `bugfix-2.1.x` code?

Yes, and the problem still exists.

### Bug Description

even though it seems to work fine how it is, I do receive an error/warning (red squiggles) with **ISSUE_TEMPLATE/bug_report.yml**.
```yml
name: 🪲 Report a bug
description: Create a bug report to help improve Marlin Firmware
title: "[BUG] (bug summary)"
labels: 'Bug: Potential ?'
body:
  - type: markdown
```

specfically this line `labels: 'Bug: Potential ?'`  
it says 'Incorrect type. Expected "array".' then gives a link for the correct syntax.

based on other examples, the corrected code should be
 ```yml
labels: ["Bug: Potential ?"]
```

it does help if you ever wanted to include other labels.

### Bug Timeline

11/29 - ✅ Label bug reports

### Expected behavior

should not have an error

### Actual behavior

error in form of red squiggles

### Version of Marlin Firmware

current bugfix

### Bed Leveling

None

### Your Slicer

None

### Host Software

None

### Don't forget to include

- [X] A ZIP file containing your `Configuration.h` and `Configuration_adv.h`.
